"""
hopai.models

The schema hopai expects: two tables, a typed identity column plus a
flexible JSONB properties bag on each. This split is deliberate -- real
constraints (foreign keys, NOT NULL, uniqueness) belong on real typed
columns; the properties you filter and traverse on in this library live
in JSONB, which is what lets `where=`/`via=` filter on arbitrary,
evolving attributes without a schema migration per new property.

    CREATE TABLE nodes (
        id BIGINT PRIMARY KEY,
        properties JSONB NOT NULL DEFAULT '{}'
    );
    CREATE TABLE edges (
        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        start_id BIGINT NOT NULL REFERENCES nodes(id),
        end_id   BIGINT NOT NULL REFERENCES nodes(id),
        properties JSONB NOT NULL DEFAULT '{}'
    );
    CREATE INDEX ON edges (start_id);
    CREATE INDEX ON edges (end_id);
    CREATE INDEX ON nodes USING GIN (properties);
    CREATE INDEX ON edges USING GIN (properties);

Vector fields add optional `vec_<name> real[]` columns BESIDE the
properties bag (via Graph.migrate_vectors() -- see vectors.py):
deliberately real columns, not JSONB keys, so the GIN index and every
traversal result stay exactly as above.

If your table/column names differ, pass them to Graph() -- see core.py.
Nothing in this library requires the SQLModel classes below specifically;
they're the default, not a hard dependency of the query-building logic.
"""

from __future__ import annotations

from sqlalchemy import (
    BigInteger, Column, ForeignKeyConstraint, Identity, Text, UniqueConstraint, text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, SQLModel

#: The graph a row belongs to. One pair of tables holds every graph, and
#: every query carries `graph_id = ...` -- so a new graph costs a string,
#: not a CREATE SCHEMA, and thousands of them are ordinary rows.
DEFAULT_GRAPH = "default"

# GENERATED BY DEFAULT, not ALWAYS: ingestion accepts rows that carry
# their own id (re-importing a graph, or ids that mean something to the
# caller) and rows that do not (let Postgres pick). ALWAYS would reject
# the first kind. See ingest.py for the sequence resync that has to
# follow a batch of explicit ids.
_IDENTITY = Identity(always=False)


class Node(SQLModel, table=True):
    __tablename__ = "nodes"
    # UNIQUE(id, graph_id) is redundant on its own -- id is already the
    # primary key -- and exists solely so edges can carry a COMPOSITE
    # foreign key. That is what makes an edge between two different
    # graphs impossible rather than merely discouraged.
    __table_args__ = (UniqueConstraint("id", "graph_id", name="uq_nodes_id_graph"),)

    id: int = Field(sa_column=Column(BigInteger, _IDENTITY, primary_key=True))
    graph_id: str = Field(
        default=DEFAULT_GRAPH,
        sa_column=Column(Text, nullable=False, server_default=text(f"'{DEFAULT_GRAPH}'")),
    )
    properties: dict = Field(
        default_factory=dict,
        sa_column=Column(JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    )


class Edge(SQLModel, table=True):
    __tablename__ = "edges"
    # Both endpoints are tied to the edge's OWN graph_id, so an edge can
    # only ever join two nodes of its own graph. Postgres refuses the
    # write; nothing has to remember to check.
    __table_args__ = (
        ForeignKeyConstraint(["start_id", "graph_id"], ["nodes.id", "nodes.graph_id"],
                             name="fk_edges_start_same_graph"),
        ForeignKeyConstraint(["end_id", "graph_id"], ["nodes.id", "nodes.graph_id"],
                             name="fk_edges_end_same_graph"),
    )

    id: int = Field(sa_column=Column(BigInteger, Identity(always=False), primary_key=True))
    graph_id: str = Field(
        default=DEFAULT_GRAPH,
        sa_column=Column(Text, nullable=False, server_default=text(f"'{DEFAULT_GRAPH}'")),
    )
    # Explicit BigInteger: SQLModel would infer plain INTEGER from the
    # annotation, which does not match a BIGINT primary key and quietly
    # caps the graph at two billion nodes.
    start_id: int = Field(sa_column=Column(BigInteger, nullable=False))
    end_id: int = Field(sa_column=Column(BigInteger, nullable=False))
    properties: dict = Field(
        default_factory=dict,
        sa_column=Column(JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    )
